### PR TITLE
Update nginx template

### PR DESCRIPTION
**Pull request by neolyte**
Update Nginx template:

- Move obsolete 'ssl' directive to the 'listen' directive instead [http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl)
- Add option to enable http2 for nginx with ssl [http://nginx.org/en/docs/http/ngx_http_v2_module.html](http://nginx.org/en/docs/http/ngx_http_v2_module.html)

### CODE REVIEW

**Comment by seuros** [comment]
I think http should be default now. Do you want to update your PR ?

**Comment by neolyte** [comment]
> I think http should be default now. Do you want to update your PR ?

I'm not sure I understand what you mean. Which http default are you referring to?

**Comment by neolyte** [comment]
You're right - this should be all good now !

**Comment by seuros** [comment]
Awesome
can you squash your PRs ? The 2 first ones don't have your name/email.

**Comment by neolyte** [comment]
Is that better now?

**Pull request merged**
