### PR TITLE
Ability to customize before_fork hook

### PR DESCRIPTION
**Pull request by yukas**
Needed in order to setup PumaWorkerKiller

### CODE REVIEW

**Comment by seuros** [comment]
before_fork can be a pretty complex code of code.
you can place a file in config/deploy/templates/puma.rb and it will be uploaded instead.

**Comment by yukas** [comment]
@seuros didn't know that, actually. Is there some documentation for that?

**Comment by seuros** [comment]
No yet :crying_cat_face: .

**Comment by seuros** [comment]
It won't combine the file. It will use the one you provided.

**Pull request closed without merging**
