### PR TITLE
Add systemd support and puma 5 support

### LINKED ISSUE #297: Support for Puma 5.0
Hi,

Would be nice to have puma 5.0 support :)

At least one breaking change is due:
- `set :puma_daemonize` option should be removed  as daemonization is gone in 5.0.

### PR DESCRIPTION
**Pull request by ayamomiji**
Fix #297 
Tested with generated puma.rb
Tested with puma 4 and 5 with rvm and rbenv

### CODE REVIEW

**Comment by S3od22** [comment]
ا

**Review by S3od22 — APPROVED** [review]

**Review by S3od22 — APPROVED** [review]

**Comment by seuros** [comment]
@S3od22 @ayamomiji , i pushed a new version that dont create another namespace for the start/stop tasks.
Can you tell me your feedback.

Also @ayamomiji , how did you fix the $HOME in the systemd service ? SystemD require an absolute path.

**Comment by attenzione** [comment]
@seuros +1 for same namespace for tasks and extraction of daemon plugin.
I've left few comments in your commit, please review them ;)

**Comment by seuros** [comment]
thank you @attenzione .

**Comment by attenzione** [comment]
Have you seen another comment? https://github.com/seuros/capistrano-puma/commit/24b91a7e1fc9442f9630f1f684885a281feaf1ae#r43833430
Seems this will be an issue

**Pull request merged**
