### PR TITLE
Add tests and CI

### PR DESCRIPTION
**Pull request by willnet**
Deploying with Capistrano and systemd can be difficult to verify manually, so I automated the verification using tests and CI. I used a Debian Docker image to create a container running systemd, and deployed a small Sinatra application to confirm it works.

With mostly default settings, I confirmed that the four tasks `puma:install`, `deploy`, `puma:stop`, and `puma:start` work as expected. It would be good to also verify other tasks and the nginx configuration, but for now, this provides the minimum necessary verification.

Running the tests revealed two issues, which I was able to fix. For details, please refer to the descriptions of each commit.

All tests from Ruby 2.5 to 3.3 have passed, as shown in the following link:

[Fix ci on Ruby 2.5 · willnet/capistrano-puma@9a83087](https://github.com/willnet/capistrano-puma/actions/runs/9851792840)

Ideally, this PR should be merged and version 6.0.0 released. However, if there is no response, I will consider releasing a forked gem.

### CODE REVIEW

**Comment by climatebrad** [comment]
@willnet would you be willing to fork? I think @seuros has abandoned this gem.

**Comment by seuros** [comment]
I didn't. 

I will release all this week.

**Review by seuros — APPROVED** [review]

**Comment by willnet** [comment]
@seuros Looking forward to the release!

**Comment by willnet** [comment]
The tests corresponding to this PR failed because the branch used to retrieve the test application was set to master. Once this PR is merged, the tests should pass.

You can see that the error occurs while running `git archive master test/app` from the link below.

[Add tests and CI · seuros/capistrano-puma@b53f608](https://github.com/seuros/capistrano-puma/actions/runs/9851951972/job/28432486602#step:4:384)

**Comment by seuros** [comment]
> @seuros Looking forward to the release!


I installed github mobile recently and started to get notifications now. 

Previously emails digest will show only if I was referenced.

**Pull request merged**
