### PR TITLE
fix the issue that `sudo` tasks hang on password input.

### PR DESCRIPTION
**Pull request by hardywu**
The sudo related tasks hang on the password input. It may be due to the deprecation of `sudo`  in Capistrano 3. So I walkaround the issue by utilizing the `ask` method.

### CODE REVIEW

**Comment by olance** [comment]
:+1: 
Just spent an hour configuring visudo.... would love this to be merged ^^

**Comment by seuros** [comment]
I think this helper should be part of capistrano so other gems can use it.
ping @leehambley , @kirs

**Comment by leehambley** [comment]
https://github.com/capistrano/sshkit#interactive-commands

**Comment by robd** [comment]
Hi all

I am working up native support for interactive sudo in SSHKit, and [interactive commands](https://github.com/capistrano/sshkit#interactive-commands) are the first part of this. These are in SSHKit master, but unreleased - you could look to use an `interaction_handler` in your `sudo_command` method to remove the pipe.

The other [part of this problem](https://github.com/capistrano/sshkit/pull/234#issuecomment-99062791) is to work on the Command Map, so that calls to `sudo` can be mapped to use an interactive sudo interaction handler in one place. I hope this will also make sure that users can hook interactive sudo on any gem without having to monkey patch.

This is parked as I work on some unrelated cleanup in SSHKit, but I hope to be able to resume work on this soon.

**Comment by leehambley** [comment]
Thanks for chiming in here @robd I didn't want to force more work down your throat, just to put this issue on your radar as another possible use-case, and as evidence that your work is having a profound and useful impact :)

**Comment by robd** [comment]
@leehambley no probs - thank you. It's useful to be made aware of issues related to my work so please keep them coming.

**Comment by mathieugagne** [comment]
:+1: I do not have sudo access but I do have write access to my nginx install directory. Can't use this feature unless it is sudoless

**Comment by robd** [comment]
I'm not exactly sure which `sudo` method is being called here, but if it is the one in the capistrano dsl, would it work to just override it like this?

```ruby
# Bottom of Capfile
module Capistrano
  module DSL
    def sudo(*args)
      execute(*args)
    end
  end
end
```

**Comment by mathieugagne** [comment]
`sudo` methods for nginx_conf:
https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/nginx.cap#L6

Yeah I could. Since the code is not that complicated I just took the parts of the gem I was interested in. start/stop/restart.. methods are done with runit in my case so I had to override quite a few parts. I basically took the templates and merged them with my recipes.

Thanks!

**Pull request closed without merging**
