### PR TITLE
Phased restart

### PR DESCRIPTION
**Pull request by mksvdmtr**
Added the ability to phased restart puma
Need to define a release directory in config/puma.rb:
`directory '/var/www/current'`
Otherwise, Puma won't pick up your new changes when running phased restarts

### CODE REVIEW

**Comment by germanotm** [comment]
Any predictions about when this pull request will be accepted?

**Comment by pocke** [comment]
I agree with this PR.
Probably this issue is related to this PR. https://github.com/seuros/capistrano-puma/issues/303
The current signal, `TSTP`, does nothing for puma. It looks a bug. So I think replacing `TSTP` with `USR1` is the right way.

**Comment by odarriba** [comment]
We need this PR also!

**Comment by seuros** [comment]
@mksvdmtr Will have this released this week. can you rebase this PR ?

**Comment by mksvdmtr** [comment]
> @mksvdmtr Will have this released this week. can you rebase this PR ?

@seuros done

**Comment by mksvdmtr** [comment]
> @mksvdmtr Will have this released this week. can you rebase this PR ?

@seuros done

**Comment by seuros** [comment]
I will release a beta version now. Let me know if you find any regression.

**Comment by phylor** [comment]
@seuros Is there any interest in making this new behavior configurable?

Some arguments against this new behavior:

- Phased restarts are only useful for zero downtime deployments. At least for Rails these are not the standard case though. I would argue that the defaults should consider the most common case (think of `rails new` and then deploy).
- Using phased restarts, the old and new application may run concurrently. This is an issue if you are running database migrations which do not comply with zero downtime deployments. In this scenario, it is possible that either your old or your new application errors out because the database has changed.
- The puma master process is not restarted using phased restarts. Updating the puma gem will hence require a manual intervention (explicitly restarting puma).
- At least in my test, Puma didn't catch up on the new application. Possibly, the `directory` configuration in puma is now mandatory (as mentioned in this PR).

I think it's a good idea to support phased restarts. But I believe that shouldn't be the default as it requires much more work and insight, and introduces more issues if not aware of it.

I would therefore suggest to revert the default back to a puma hot restart. For those who need zero downtime deployments, they could enable a configuration option to activate it.

What are your thoughts about this?

**Comment by seuros** [comment]
@phylor yes. I agree with you .
 Do you have time to open a PR ? I might be able to do it this weekend.

**Pull request merged**
